### ISSUE TITLE
Link to https://parafem.org.uk/ is not about ParaFEM

### ISSUE THREAD

**Issue by Beliavsky** [ParaFEM/ParaFEM#7]
The link to https://parafem.org.uk/ is not about ParaFEM.

**Comment by leemargetts** [comment]
Thanks for the message. It was about ParaFEM. I have a ticket open with the web hosting company to find out what happened to the content and to see it they can restore it. They've been doing some migrations.

**Comment by leemargetts** [comment]
The web hosting company have fixed the problem that they have caused. The ParaFEM website has been restored.
